// tslint:disable
// @ts-nocheck
/** This file is autogenerated. Do not edit */
import { ABCSkeleton } from "./skeleton/ABCSkeleton";

class Router {
    public static async route(message: any): Promise<void> {
        switch (message.__type__) {
            case 'abc-pippo':
                await ABCSkeleton.pippo(message);
                break;
            case 'abc-paperino':
                await ABCSkeleton.paperino(message);
                break;
            case 'abc-pluto':
                await ABCSkeleton.pluto(message);
                break;
            default:
                console.error('[TEST] Cannot route', message.type);
        }
    }
}

// @ts-ignore
onmessage = async (message: MessageEvent) => await Router.route(message.data);
